name: shopthoitrang_mobile
publish_to: 'none'
description: Ứng dụng Flutter cho khách hàng Shop Thời Trang
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  intl: ^0.19.0

  # Routing
  go_router: ^14.1.4

  # UI
  flutter_svg: ^2.0.10+1

  # JWT decode (tùy chọn)
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
